spring:
  application:
    name: eureka-consumer-feign
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 0.1 #设置Sleuth的抽样收集概率

server:
  port: 20002
  servlet:
    context-path: /

eureka:
  instance:
    instance-id: ${spring.application.name}-@project.version@:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://localhost:23333/eureka/
